name: CI

on:
  schedule:
    - cron: '* 3-10 * * 1-5'
  workflow_dispatch:
  push:

env:
  BOT: ${{ secrets.BOT }}
  CHAT: ${{ secrets.CHAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - name: Run Script
      run: |
        gem install telegram-bot-ruby
        ruby script.rb
    - name: Keep repository actions alive
      uses: gautamkrishnar/keepalive-workflow@v1
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
